// Build script — scans `web/dist/` and emits a `static_assets.rs`
// fragment that the crate `include!`s at compile time. The fragment
// is a `&[(&str, &[u8], &str)]` slice of (route_path, bytes,
// content_type), which the request dispatcher in `src/lib.rs` walks
// linearly when a `/static/<chunk>.js` request arrives.
//
// Why a build script instead of `include_dir!`: code splitting
// (esbuild ESM + splitting=true) emits chunks named with content
// hashes — `chunk-ZZ3EB4DS.js` — that change every build. We can't
// hard-code `include_bytes!` calls per chunk; we have to discover
// them at build time. Using a tiny `build.rs` over a third-party
// `include_dir` macro keeps the dependency surface minimal.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let dist = Path::new(&manifest_dir).join("web").join("dist");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let out_path = Path::new(&out_dir).join("static_assets.rs");

    // Re-run when any chunk in dist/ changes. Cargo's directory-watch
    // is shallow, so we list explicit files. We also re-run if the
    // dist directory itself changes (new file added/removed).
    println!("cargo:rerun-if-changed={}", dist.display());

    let mut entries: Vec<(String, PathBuf)> = Vec::new();
    if let Ok(rd) = fs::read_dir(&dist) {
        for ent in rd.flatten() {
            let p = ent.path();
            if !p.is_file() {
                continue;
            }
            let name = match p.file_name().and_then(|n| n.to_str()) {
                Some(n) => n.to_string(),
                None => continue,
            };
            // We bake in `live.html` separately via include_str!. The
            // metafile is dev-only output. Skip both. CSS is inlined
            // into live.html, but we also serve it for any client that
            // requests it directly (devtools sourcemap fetches, etc.)
            if name == "live.html" || name == "metafile.json" {
                continue;
            }
            // Guard against accidentally serving sourcemaps in release.
            if name.ends_with(".js.map") || name.ends_with(".css.map") {
                continue;
            }
            println!("cargo:rerun-if-changed={}", p.display());
            entries.push((name, p));
        }
    }
    entries.sort();

    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by build.rs from web/dist/. Do not edit.\n");
    out.push_str("pub static STATIC_ASSETS: &[(&str, &[u8], &str)] = &[\n");
    for (name, path) in &entries {
        let route = format!("/static/{name}");
        let ct = guess_content_type(name);
        // Cargo passes the absolute path to include_bytes! through OUT_DIR.
        out.push_str(&format!(
            "    (\"{route}\", include_bytes!(r\"{}\"), \"{ct}\"),\n",
            path.display()
        ));
    }
    out.push_str("];\n");

    fs::write(&out_path, out).expect("write static_assets.rs");
}

fn guess_content_type(name: &str) -> &'static str {
    if name.ends_with(".js") {
        "application/javascript; charset=utf-8"
    } else if name.ends_with(".css") {
        "text/css; charset=utf-8"
    } else if name.ends_with(".map") {
        "application/json"
    } else if name.ends_with(".svg") {
        "image/svg+xml"
    } else if name.ends_with(".png") {
        "image/png"
    } else {
        "application/octet-stream"
    }
}
