/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe. */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Repo + version + index status one-shot. */
        get: operations["getBootstrap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent tool-call activity tail. */
        get: operations["getActivity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List agent runs (running + recently exited). */
        get: operations["listAgents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{id}/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tail an agent's log file incrementally. */
        get: operations["getAgentLog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{id}/tail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tail diagnostic for an agent run (free-form). */
        get: operations["getAgentTail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{id}/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Single-agent metadata snapshot. */
        get: operations["getAgentInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{id}/kill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send SIGTERM/SIGKILL to a running agent. */
        post: operations["killAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/launch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Launch a new agent run. */
        post: operations["launchAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent-profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List per-crate agent profiles. */
        get: operations["listAgentProfiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent-kills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent agent-guard kill events. */
        get: operations["listAgentKills"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent-models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List cataloged models. */
        get: operations["listAgentModels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ollama-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ollama auth-stack key snapshot (mode/mtime/value). */
        get: operations["getOllamaKey"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service-discovery report (issue */
        get: operations["getServices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/telemetry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** KPI event stream tail. */
        get: operations["getTelemetry"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/telemetry/otlp-health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OTLP collector reachability probe. */
        get: operations["getOtlpHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reindex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run a full re-index against the server's PWD. */
        post: operations["reindexPwd"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/random-query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fire one random `crabcc` query — used by the dashboard's "random query" button to exercise the surface. */
        post: operations["randomQuery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Call-graph snapshot (legacy/internal — schema tracked opaquely until the call-graph viewer migrates fully). */
        get: operations["getGraph"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/seed-graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Seed nodes for the graph viewer (legacy). */
        get: operations["seedGraph"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/debug/dump": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Diagnostic dump — internal-only debug surface. */
        get: operations["debugDump"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent crabcc-memory drawers. */
        get: operations["getMemoryRecent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Server-Sent Events stream — event: activity and event: agents topics. */
        get: operations["getEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
        };
        Bootstrap: {
            repo: string;
            root: string;
            version: string;
            index?: {
                present?: boolean;
                files?: number;
                symbols?: number;
            };
        };
        ActivityHit: {
            /** @description unix seconds */
            ts: number;
            op: string;
            query: string;
            count: number;
            source?: string;
        };
        ActivityResponse: {
            items: components["schemas"]["ActivityHit"][];
        };
        AgentSummary: {
            id: string;
            /** @enum {string} */
            status: "running" | "exited";
            pid?: number;
            prompt_preview?: string;
            model?: string;
            started_ts?: number;
            exit_code?: number | null;
        };
        AgentsResponse: {
            agents: components["schemas"]["AgentSummary"][];
        };
        AgentLog: {
            body: string;
            cursor: number;
            total: number;
        };
        AgentLaunchRequest: {
            prompt: string;
            model?: string;
            /** @enum {string} */
            backend?: "ollama" | "anthropic";
        };
        AgentLaunchResponse: {
            id: string;
            pid?: number;
        };
        AgentProfileEntry: {
            id: string;
            /**
             * @description Trailing underscore mirrors the Rust struct field — `crate`
             *     is a reserved keyword.
             */
            crate_: string | null;
            description: string | null;
            model: string | null;
        };
        AgentProfilesResponse: {
            dir: string;
            profiles: components["schemas"]["AgentProfileEntry"][];
        };
        AgentKillRow: {
            run_id: string;
            reason: string;
            pid: number | null;
            detail: string | null;
            /** @description unix seconds */
            killed_at: number;
        };
        AgentKillsResponse: {
            db: string;
            rows: components["schemas"]["AgentKillRow"][];
        };
        AgentModelEntry: {
            file: string;
            provider: string;
            name: string;
            params: string | null;
            context: number | null;
            docs_first: string | null;
        };
        AgentModelsResponse: {
            dir: string;
            models: components["schemas"]["AgentModelEntry"][];
        };
        OllamaKey: {
            present: boolean;
            path: string;
            mode: string | null;
            mtime_secs: number | null;
            size_bytes: number | null;
            key: string | null;
        };
        ServiceStatus: {
            name: string;
            /** @enum {string} */
            kind: "redis" | "http_json_api" | "otlp_grpc" | "otlp_http" | "ollama" | "generic";
            url: string;
            /** @description Env-var name OR the literal "default". */
            source: string;
            host: string;
            port: number;
            reachable: boolean;
            latency_ms: number;
            error: string | null;
            /** @description unix seconds */
            probed_at: number;
        };
        DiscoveryReport: {
            services: components["schemas"]["ServiceStatus"][];
            compose_mode: boolean;
            elapsed_ms: number;
        };
        TelemetryEvent: {
            /** @description unix seconds */
            ts: number;
            /** @enum {string} */
            level: "TRACE" | "DEBUG" | "INFO" | "WARN" | "ERROR";
            target: string;
            fields: {
                [key: string]: unknown;
            };
        };
        TelemetrySource: {
            path: string;
            lines_read: number;
            bytes: number;
            exists: boolean;
        };
        TelemetrySnapshot: {
            cursor: number;
            events: components["schemas"]["TelemetryEvent"][];
            source: components["schemas"]["TelemetrySource"];
        };
        OtlpHealth: {
            reachable: boolean;
            endpoint: string;
            error?: string | null;
        };
        ReindexReport: {
            root: string;
            elapsed_ms: number;
            stats: {
                [key: string]: string | number;
            };
            logs: string[];
        };
        RandomQueryResponse: {
            op: string;
            symbol: string;
        };
    };
    responses: never;
    parameters: {
        /** @description Unix-seconds cursor — return rows newer than this. */
        SinceTs: number;
        /** @description Max rows to return. */
        Limit: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getBootstrap: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bootstrap snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bootstrap"];
                };
            };
        };
    };
    getActivity: {
        parameters: {
            query?: {
                /** @description Unix-seconds cursor — return rows newer than this. */
                since?: components["parameters"]["SinceTs"];
                /** @description Max rows to return. */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Activity tail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityResponse"];
                };
            };
        };
    };
    listAgents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agents. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentsResponse"];
                };
            };
        };
    };
    getAgentLog: {
        parameters: {
            query?: {
                since?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Log slice. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentLog"];
                };
            };
        };
    };
    getAgentTail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tail snapshot (free-form for now). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    getAgentInfo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agent info (free-form for now). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    killAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Kill snapshot (free-form for now). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    launchAgent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentLaunchRequest"];
            };
        };
        responses: {
            /** @description Launched. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentLaunchResponse"];
                };
            };
        };
    };
    listAgentProfiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profiles. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentProfilesResponse"];
                };
            };
        };
    };
    listAgentKills: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Kills. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentKillsResponse"];
                };
            };
        };
    };
    listAgentModels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Models. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentModelsResponse"];
                };
            };
        };
    };
    getOllamaKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Key snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OllamaKey"];
                };
            };
        };
    };
    getServices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Discovery report. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoveryReport"];
                };
            };
        };
    };
    getTelemetry: {
        parameters: {
            query?: {
                /** @description Unix-seconds cursor — return rows newer than this. */
                since?: components["parameters"]["SinceTs"];
                /** @description Max rows to return. */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Telemetry tail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelemetrySnapshot"];
                };
            };
        };
    };
    getOtlpHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OTLP health. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OtlpHealth"];
                };
            };
        };
    };
    reindexPwd: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reindex report. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReindexReport"];
                };
            };
        };
    };
    randomQuery: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Random query echo. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RandomQueryResponse"];
                };
            };
        };
    };
    getGraph: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Graph snapshot (free-form JSON for now). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    seedGraph: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Seed nodes (free-form JSON for now). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    debugDump: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dump (free-form JSON). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    getMemoryRecent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Memory tail (free-form for now; tracked opaquely until the memory dashboard panel ships). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    getEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream (Content-Type text/event-stream). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
}
