// Thin typed client over the existing /api/* endpoints. One module per
// endpoint family — keeps callers free of fetch boilerplate and routes
// JSON parsing through a single typed surface so a server-side schema
// drift surfaces here, not deep in a component.
//
// Issue #170 phase 0 — the response/request shapes below are aliased
// from `api.gen.ts`, which is auto-generated by `openapi-typescript`
// from `crates/crabcc-viz/openapi.yaml`. The codegen runs as part of
// `bun run build` and `bun run dev`, so a hand-edit of api.gen.ts will
// be overwritten — change the YAML instead.

import type { components } from "./api.gen";

type Schemas = components["schemas"];

// Forge and analytics types are not yet in the codegen'd api.gen.ts,
// so we declare them inline until the next `bun run codegen` pass.
export interface PrAuthor {
  login: string;
  avatar_url: string;
}
export interface PrLabel {
  name: string;
  color: string;
}
export interface PrSummary {
  number: number;
  title: string;
  state: string;
  draft: boolean;
  merged: boolean;
  author: PrAuthor;
  head_ref: string;
  base_ref: string;
  created_at: string;
  updated_at: string;
  labels: PrLabel[];
  additions: number;
  deletions: number;
  changed_files: number;
  html_url: string;
  body?: string;
}
export interface PrFile {
  filename: string;
  status: string;
  additions: number;
  deletions: number;
  patch?: string;
  previous_filename?: string;
}
export interface PrDetail {
  pr: PrSummary;
  files: PrFile[];
  files_truncated: boolean;
}
export interface PrListResponse {
  prs: PrSummary[];
  repo: string;
  total: number;
  page: number;
}
export interface ImpactNode {
  id: string;
  label: string;
  file: string;
  kind: string;
  changed: boolean;
  depth: number;
  line?: number;
}
export interface ImpactEdge {
  src: string;
  dst: string;
}
export interface PrImpactGraph {
  pr_number: number;
  changed_files: string[];
  nodes: ImpactNode[];
  edges: ImpactEdge[];
  direct_symbols: number;
  impacted_symbols: number;
  truncated: boolean;
}
export interface HotspotFile {
  file: string;
  commits: number;
  churn_lines?: number;
  authors: number;
  first_seen: string;
  last_seen: string;
}
export interface HotspotsResponse {
  hotspots: HotspotFile[];
  head_sha: string;
  computed_at: number;
  total_commits_scanned: number;
  total_files_seen: number;
}
export interface DeadSymbol {
  name: string;
  kind: string;
  file: string;
  line: number;
}
export interface DeadcodeResponse {
  dead_code: DeadSymbol[];
  head_sha: string;
  computed_at: number;
}

export type Bootstrap = Schemas["Bootstrap"];
export type SavingsBucket = Schemas["SavingsBucket"];
/** Live token-savings aggregate (/api/savings). by_op is keyed by op
 *  name (sym/refs/read/media/rewrite/morph/...). */
export interface Savings {
  session: SavingsBucket;
  last_24h: SavingsBucket;
  all_time: SavingsBucket;
  by_op: Record<string, SavingsBucket>;
}
export type ActivityHit = Schemas["ActivityHit"];
export type AgentSummary = Schemas["AgentSummary"];
export type AgentLog = Schemas["AgentLog"];
export type ReindexReport = Schemas["ReindexReport"];
export type TelemetryEvent = Schemas["TelemetryEvent"];
export type TelemetrySource = Schemas["TelemetrySource"];
export type TelemetrySnapshot = Schemas["TelemetrySnapshot"];
export type NetlogResponse = Schemas["NetlogResponse"];
export type NetlogEvent = Schemas["NetlogEvent"];
export type OtlpHealth = Schemas["OtlpHealth"];
export type AgentProfileEntry = Schemas["AgentProfileEntry"];
export type AgentKillRow = Schemas["AgentKillRow"];
export type AgentModelEntry = Schemas["AgentModelEntry"];
export type ServiceStatus = Schemas["ServiceStatus"];
export type DiscoveryReport = Schemas["DiscoveryReport"];
export type OllamaKey = Schemas["OllamaKey"];
export type RandomQueryResponse = Schemas["RandomQueryResponse"];

type ActivityResponse = Schemas["ActivityResponse"];
type AgentsResponse = Schemas["AgentsResponse"];
type AgentProfilesResponse = Schemas["AgentProfilesResponse"];
type AgentKillsResponse = Schemas["AgentKillsResponse"];
type AgentModelsResponse = Schemas["AgentModelsResponse"];

async function getJson<T>(path: string): Promise<T> {
  const r = await fetch(path);
  if (!r.ok) {
    const body = await r.text().catch(() => "");
    throw new Error(`${r.status} ${r.statusText}: ${body}`);
  }
  return (await r.json()) as T;
}

async function postJson<T>(path: string, body?: unknown): Promise<T> {
  const r = await fetch(path, {
    method: "POST",
    headers: body ? { "Content-Type": "application/json" } : undefined,
    body: body ? JSON.stringify(body) : undefined,
  });
  if (!r.ok) throw new Error(`${r.status} ${r.statusText}: ${await r.text()}`);
  return (await r.json()) as T;
}

export const api = {
  bootstrap: () => getJson<Bootstrap>("/api/bootstrap"),
  activity: (sinceTs?: number, limit = 100) =>
    getJson<ActivityResponse>(
      `/api/activity?since=${sinceTs ?? 0}&limit=${limit}`,
    ),
  savings: () => getJson<Savings>("/api/savings"),
  agents: () => getJson<AgentsResponse>("/api/agents"),
  agentLog: (id: string, since: number) =>
    getJson<AgentLog>(`/api/agents/${id}/log?since=${since}`),
  agentProfiles: () =>
    getJson<AgentProfilesResponse>("/api/agent-profiles"),
  agentKills: () => getJson<AgentKillsResponse>("/api/agent-kills"),
  agentModels: () => getJson<AgentModelsResponse>("/api/agent-models"),
  ollamaKey: () => getJson<OllamaKey>("/api/ollama-key"),
  services: () => getJson<DiscoveryReport>("/api/services"),
  reindex: () => postJson<ReindexReport>("/api/reindex"),
  randomQuery: () => postJson<RandomQueryResponse>("/api/random-query"),
  netlog: (sinceTs?: number, limit = 100) =>
    getJson<NetlogResponse>(
      `/api/netlog?since=${sinceTs ?? 0}&limit=${limit}`,
    ),
  telemetry: (sinceTs?: number, limit = 100) =>
    getJson<TelemetrySnapshot>(
      `/api/telemetry?since=${sinceTs ?? 0}&limit=${limit}`,
    ),
  // Issue #86 — OTLP health probe. Returns green/red pill data for /live.
  otlpHealth: () => getJson<OtlpHealth>("/api/telemetry/otlp-health"),
  // Forge (GitHub/Gitea)
  forgePrs: (state = "open", page = 1) =>
    getJson<PrListResponse>(`/api/forge/prs?state=${state}&page=${page}`),
  forgePr: (number: number) =>
    getJson<PrDetail>(`/api/forge/prs/${number}`),
  forgePrImpact: (number: number) =>
    getJson<PrImpactGraph>(`/api/forge/prs/${number}/impact`),
  // Analytics
  analyticsHotspots: (limit = 50) =>
    getJson<HotspotsResponse>(`/api/analytics/hotspots?limit=${limit}`),
  analyticsDeadcode: (limit = 100) =>
    getJson<DeadcodeResponse>(`/api/analytics/deadcode?limit=${limit}`),
};

// Issue #112 follow-up — expose the api surface on window for
// Chrome DevTools console use. Devs can call `window.crabcc.agents()`,
// `window.crabcc.agentKills()`, etc. directly. Logged once on first
// import so the console hint shows up before the React tree mounts.
declare global {
  interface Window {
    crabcc?: typeof api;
  }
}
if (typeof window !== "undefined") {
  window.crabcc = api;
  // Friendly console banner — readable in Chrome DevTools / Safari Web Inspector.
  // eslint-disable-next-line no-console
  console.info(
    "%ccrabcc%c live dashboard — call %cwindow.crabcc%c.{agents, agentProfiles, agentKills, agentModels, telemetry, ...}() to query the running server.",
    "color:#ff2a6d;font-weight:700;text-shadow:0 0 4px rgba(255,42,109,.5);",
    "color:#c8d4ff;",
    "color:#00f0ff;font-weight:700;",
    "color:#c8d4ff;",
  );
}
