// Thin typed client over the existing /api/* endpoints. One module per
// endpoint family — keeps callers free of fetch boilerplate and routes
// JSON parsing through a single typed surface so a server-side schema
// drift surfaces here, not deep in a component.
//
// Issue #170 phase 0 — the response/request shapes below are aliased
// from `api.gen.ts`, which is auto-generated by `openapi-typescript`
// from `crates/crabcc-viz/openapi.yaml`. The codegen runs as part of
// `bun run build` and `bun run dev`, so a hand-edit of api.gen.ts will
// be overwritten — change the YAML instead.

import type { components } from "./api.gen";

type Schemas = components["schemas"];

export type Bootstrap = Schemas["Bootstrap"];
export type ActivityHit = Schemas["ActivityHit"];
export type AgentSummary = Schemas["AgentSummary"];
export type AgentLog = Schemas["AgentLog"];
export type ReindexReport = Schemas["ReindexReport"];
export type TelemetryEvent = Schemas["TelemetryEvent"];
export type TelemetrySource = Schemas["TelemetrySource"];
export type TelemetrySnapshot = Schemas["TelemetrySnapshot"];
export type OtlpHealth = Schemas["OtlpHealth"];
export type AgentProfileEntry = Schemas["AgentProfileEntry"];
export type AgentKillRow = Schemas["AgentKillRow"];
export type AgentModelEntry = Schemas["AgentModelEntry"];
export type ServiceStatus = Schemas["ServiceStatus"];
export type DiscoveryReport = Schemas["DiscoveryReport"];
export type OllamaKey = Schemas["OllamaKey"];
export type RandomQueryResponse = Schemas["RandomQueryResponse"];

type ActivityResponse = Schemas["ActivityResponse"];
type AgentsResponse = Schemas["AgentsResponse"];
type AgentProfilesResponse = Schemas["AgentProfilesResponse"];
type AgentKillsResponse = Schemas["AgentKillsResponse"];
type AgentModelsResponse = Schemas["AgentModelsResponse"];

async function getJson<T>(path: string): Promise<T> {
  const r = await fetch(path);
  if (!r.ok) throw new Error(`${r.status} ${r.statusText}`);
  return (await r.json()) as T;
}

async function postJson<T>(path: string, body?: unknown): Promise<T> {
  const r = await fetch(path, {
    method: "POST",
    headers: body ? { "Content-Type": "application/json" } : undefined,
    body: body ? JSON.stringify(body) : undefined,
  });
  if (!r.ok) throw new Error(`${r.status} ${r.statusText}: ${await r.text()}`);
  return (await r.json()) as T;
}

export const api = {
  bootstrap: () => getJson<Bootstrap>("/api/bootstrap"),
  activity: (sinceTs?: number, limit = 100) =>
    getJson<ActivityResponse>(
      `/api/activity?since=${sinceTs ?? 0}&limit=${limit}`,
    ),
  agents: () => getJson<AgentsResponse>("/api/agents"),
  agentLog: (id: string, since: number) =>
    getJson<AgentLog>(`/api/agents/${id}/log?since=${since}`),
  agentProfiles: () =>
    getJson<AgentProfilesResponse>("/api/agent-profiles"),
  agentKills: () => getJson<AgentKillsResponse>("/api/agent-kills"),
  agentModels: () => getJson<AgentModelsResponse>("/api/agent-models"),
  ollamaKey: () => getJson<OllamaKey>("/api/ollama-key"),
  services: () => getJson<DiscoveryReport>("/api/services"),
  reindex: () => postJson<ReindexReport>("/api/reindex"),
  randomQuery: () => postJson<RandomQueryResponse>("/api/random-query"),
  telemetry: (sinceTs?: number, limit = 100) =>
    getJson<TelemetrySnapshot>(
      `/api/telemetry?since=${sinceTs ?? 0}&limit=${limit}`,
    ),
  // Issue #86 — OTLP health probe. Returns green/red pill data for /live.
  otlpHealth: () => getJson<OtlpHealth>("/api/telemetry/otlp-health"),
};

// Issue #112 follow-up — expose the api surface on window for
// Chrome DevTools console use. Devs can call `window.crabcc.agents()`,
// `window.crabcc.agentKills()`, etc. directly. Logged once on first
// import so the console hint shows up before the React tree mounts.
declare global {
  interface Window {
    crabcc?: typeof api;
  }
}
if (typeof window !== "undefined") {
  window.crabcc = api;
  // Friendly console banner — readable in Chrome DevTools / Safari Web Inspector.
  // eslint-disable-next-line no-console
  console.info(
    "%ccrabcc%c live dashboard — call %cwindow.crabcc%c.{agents, agentProfiles, agentKills, agentModels, telemetry, ...}() to query the running server.",
    "color:#ff2a6d;font-weight:700;text-shadow:0 0 4px rgba(255,42,109,.5);",
    "color:#c8d4ff;",
    "color:#00f0ff;font-weight:700;",
    "color:#c8d4ff;",
  );
}
