/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe. */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/openapi.yaml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Echo the hand-maintained OpenAPI 3.1 spec for this server (#172).
         * @description Returns the same `openapi.yaml` content the dashboard's drift test
         *     validates against. Lets the planned `com.crabcc.docs.api` Scalar
         *     container render the spec without a separate file copy — fetch
         *     from `crabcc serve`, render, done.
         */
        get: operations["getOpenapiYaml"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Repo + version + index status one-shot. */
        get: operations["getBootstrap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent tool-call activity tail. */
        get: operations["getActivity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/netlog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Outbound-egress tail — recent infra HTTP + allowlist violations (#160). */
        get: operations["getNetlog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/savings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live token-savings aggregate (session / last 24h / all-time + per-op). */
        get: operations["getSavings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List agent runs (running + recently exited). */
        get: operations["listAgents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{id}/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tail an agent's log file incrementally. */
        get: operations["getAgentLog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{id}/tail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tail diagnostic for an agent run (free-form). */
        get: operations["getAgentTail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{id}/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Single-agent metadata snapshot. */
        get: operations["getAgentInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{id}/kill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send SIGTERM/SIGKILL to a running agent. */
        post: operations["killAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/launch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Launch a new agent run. */
        post: operations["launchAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent-profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List per-crate agent profiles. */
        get: operations["listAgentProfiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent-kills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent agent-guard kill events. */
        get: operations["listAgentKills"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent-models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List cataloged models. */
        get: operations["listAgentModels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ollama-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ollama auth-stack key snapshot (mode/mtime/value). */
        get: operations["getOllamaKey"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service-discovery report (issue */
        get: operations["getServices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/telemetry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** KPI event stream tail. */
        get: operations["getTelemetry"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/telemetry/otlp-health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OTLP collector reachability probe. */
        get: operations["getOtlpHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reindex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run a full re-index against the server's PWD. */
        post: operations["reindexPwd"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/random-query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fire one random `crabcc` query — used by the dashboard's "random query" button to exercise the surface. */
        post: operations["randomQuery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Call-graph snapshot (legacy/internal — schema tracked opaquely until the call-graph viewer migrates fully). */
        get: operations["getGraph"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/seed-graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Seed nodes for the graph viewer.
         * @description Returns a bounded subgraph of the cached call graph rooted on
         *     the highest-degree symbols. Each node carries optional symbol
         *     metadata (kind / file / line / signature) when the id resolves
         *     in the symbol index — added in #301 so the desktop drawer can
         *     render symbol detail without a follow-up RPC.
         */
        get: operations["seedGraph"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/debug/dump": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Diagnostic dump — internal-only debug surface. */
        get: operations["debugDump"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent crabcc-memory drawers. */
        get: operations["getMemoryRecent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cross-repo aggregate substring search over crabcc-memory drawers.
         * @description Powers the /memory browser. Walks $CRABCC_HOME/repos/*\/memory.db and matches body/source_id, newest first. Pass repo=<key> to scope to one repo.
         */
        get: operations["getMemorySearch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Server-Sent Events stream — event: activity and event: agents topics. */
        get: operations["getEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forge/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GitHub/Gitea forge configuration — repo slug, token presence. */
        get: operations["getForgeConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forge/prs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List pull requests from the configured GitHub/Gitea repo. */
        get: operations["listForgePrs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forge/prs/{number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single PR with its changed-files diff. */
        get: operations["getForgePr"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forge/prs/{number}/impact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Blast-radius graph for a PR: changed symbols + their callers/callees. */
        get: operations["getForgePrImpact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/hotspots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** High-churn files ranked by commit count (fast single git-log pass). */
        get: operations["getAnalyticsHotspots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/deadcode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Functions with zero callers in the symbol index. */
        get: operations["getAnalyticsDeadcode"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wormhole/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Active wormhole transport sessions. */
        get: operations["getWormholeSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
        };
        Bootstrap: {
            repo: string;
            root: string;
            version: string;
            index?: {
                present?: boolean;
                files?: number;
                symbols?: number;
            };
        };
        ActivityHit: {
            /** @description unix seconds */
            ts: number;
            op: string;
            query: string;
            count: number;
            source?: string;
        };
        ActivityResponse: {
            items: components["schemas"]["ActivityHit"][];
        };
        NetlogEvent: {
            /** @description Unix-epoch second. */
            ts: number;
            /** @description Subsystem that made the request (morph */
            caller: string;
            op: string;
            host: string;
            port: number;
            /** @description True if the host is on the allowlist; false = blocked violation. */
            ok: boolean;
        };
        NetlogResponse: {
            /** @description Max ts returned; resend as `since`. */
            cursor: number;
            /** @description Count of returned events that were blocked. */
            violations: number;
            events: components["schemas"]["NetlogEvent"][];
        };
        SavingsBucket: {
            queries: number;
            used_tokens: number;
            saved_tokens: number;
        };
        AgentSummary: {
            id: string;
            /** @enum {string} */
            status: "running" | "exited";
            pid?: number;
            prompt_preview?: string;
            model?: string;
            started_ts?: number;
            exit_code?: number | null;
        };
        AgentsResponse: {
            agents: components["schemas"]["AgentSummary"][];
        };
        AgentLog: {
            body: string;
            cursor: number;
            total: number;
        };
        AgentLaunchRequest: {
            prompt: string;
            model?: string;
            /** @enum {string} */
            backend?: "ollama" | "anthropic";
            /**
             * @description Profile id (bare filename without `.profile.toml`). When
             *     set, the server forwards `--profile internal/<id>` to the
             *     spawned CLI. Validated against `[A-Za-z0-9_-]+` server-
             *     side; pre-#306 servers silently ignore the field.
             */
            profile?: string;
        };
        AgentLaunchResponse: {
            id: string;
            pid?: number;
        };
        AgentProfileEntry: {
            id: string;
            /**
             * @description Trailing underscore mirrors the Rust struct field — `crate`
             *     is a reserved keyword.
             */
            crate_: string | null;
            description: string | null;
            model: string | null;
        };
        AgentProfilesResponse: {
            dir: string;
            profiles: components["schemas"]["AgentProfileEntry"][];
        };
        AgentKillRow: {
            run_id: string;
            reason: string;
            pid: number | null;
            detail: string | null;
            /** @description unix seconds */
            killed_at: number;
        };
        AgentKillsResponse: {
            db: string;
            rows: components["schemas"]["AgentKillRow"][];
        };
        AgentModelEntry: {
            file: string;
            provider: string;
            name: string;
            params: string | null;
            context: number | null;
            docs_first: string | null;
        };
        AgentModelsResponse: {
            dir: string;
            models: components["schemas"]["AgentModelEntry"][];
        };
        OllamaKey: {
            present: boolean;
            path: string;
            mode: string | null;
            mtime_secs: number | null;
            size_bytes: number | null;
            key: string | null;
        };
        ServiceStatus: {
            name: string;
            /** @enum {string} */
            kind: "redis" | "http_json_api" | "otlp_grpc" | "otlp_http" | "ollama" | "generic";
            url: string;
            /** @description Env-var name OR the literal "default". */
            source: string;
            host: string;
            port: number;
            reachable: boolean;
            latency_ms: number;
            error: string | null;
            /** @description unix seconds */
            probed_at: number;
        };
        DiscoveryReport: {
            services: components["schemas"]["ServiceStatus"][];
            compose_mode: boolean;
            elapsed_ms: number;
        };
        TelemetryEvent: {
            /** @description unix seconds */
            ts: number;
            /** @enum {string} */
            level: "TRACE" | "DEBUG" | "INFO" | "WARN" | "ERROR";
            target: string;
            fields: {
                [key: string]: unknown;
            };
        };
        TelemetrySource: {
            path: string;
            lines_read: number;
            bytes: number;
            exists: boolean;
        };
        TelemetrySnapshot: {
            cursor: number;
            events: components["schemas"]["TelemetryEvent"][];
            source: components["schemas"]["TelemetrySource"];
        };
        OtlpHealth: {
            reachable: boolean;
            endpoint: string;
            error?: string | null;
        };
        ReindexReport: {
            root: string;
            elapsed_ms: number;
            stats: {
                [key: string]: string | number;
            };
            logs: string[];
        };
        RandomQueryResponse: {
            op: string;
            symbol: string;
        };
        GraphNode: {
            /** @description Symbol name as the call graph stores it. */
            id: string;
            /** @description BFS depth from the seed set (0 = seed). */
            depth: number;
            /**
             * @description Symbol kind from the index — one of `function`, `method`,
             *     `class`, `struct`, `enum`, `trait`, `interface`, `const`,
             *     `var`, `type`, `macro`. Omitted when `id` doesn't resolve
             *     in the symbol index (extern crate, std, dynamic dispatch
             *     target).
             * @enum {string}
             */
            kind?: "function" | "method" | "class" | "struct" | "enum" | "trait" | "interface" | "const" | "var" | "type" | "macro";
            /** @description Repo-relative path of the defining site. */
            file?: string;
            /** @description 1-based line number of the defining site. */
            line?: number;
            /** @description Single-line signature (e.g. `pub fn open(path: &Path) -> Result<Store>`). */
            signature?: string;
        };
        GraphEdge: {
            /** @description Caller symbol name. */
            src: string;
            /** @description Callee symbol name. */
            dst: string;
        };
        SeedSnapshot: {
            nodes: components["schemas"]["GraphNode"][];
            edges: components["schemas"]["GraphEdge"][];
            /** @description Subset of node ids that were chosen as seeds (depth 0). */
            seeds: string[];
        };
        ForgeConfig: {
            repo: string;
            configured: boolean;
            token_present: boolean;
            forge_kind: string;
            rate_limit_remaining?: number | null;
            rate_limit_reset?: number | null;
        };
        PrAuthor: {
            login: string;
            avatar_url: string;
        };
        PrLabel: {
            name: string;
            color: string;
        };
        PrSummary: {
            number: number;
            title: string;
            state: string;
            draft: boolean;
            merged: boolean;
            author: components["schemas"]["PrAuthor"];
            head_ref: string;
            base_ref: string;
            created_at: string;
            updated_at: string;
            labels: components["schemas"]["PrLabel"][];
            additions: number;
            deletions: number;
            changed_files: number;
            html_url: string;
            body?: string;
        };
        PrFile: {
            filename: string;
            status: string;
            additions: number;
            deletions: number;
            patch?: string;
            previous_filename?: string;
        };
        PrDetail: {
            pr: components["schemas"]["PrSummary"];
            files: components["schemas"]["PrFile"][];
            /** @description True when the PR has >300 changed files and the list is capped. */
            files_truncated: boolean;
        };
        PrListResponse: {
            prs: components["schemas"]["PrSummary"][];
            repo: string;
            total: number;
            page: number;
        };
        ImpactNode: {
            id: string;
            label: string;
            file: string;
            kind: string;
            changed: boolean;
            depth: number;
            line?: number;
        };
        ImpactEdge: {
            src: string;
            dst: string;
        };
        PrImpactGraph: {
            pr_number: number;
            changed_files: string[];
            nodes: components["schemas"]["ImpactNode"][];
            edges: components["schemas"]["ImpactEdge"][];
            direct_symbols: number;
            impacted_symbols: number;
            truncated: boolean;
        };
        HotspotFile: {
            file: string;
            commits: number;
            /** @description Total lines added + removed (null until numstat is wired). */
            churn_lines?: number | null;
            authors: number;
            first_seen: string;
            last_seen: string;
        };
        HotspotsResponse: {
            hotspots: components["schemas"]["HotspotFile"][];
            head_sha: string;
            computed_at: number;
            total_commits_scanned: number;
            total_files_seen: number;
        };
        DeadSymbol: {
            name: string;
            kind: string;
            file: string;
            line: number;
        };
        DeadcodeResponse: {
            dead_code: components["schemas"]["DeadSymbol"][];
            head_sha: string;
            computed_at: number;
        };
        WormholeSession: {
            session_hex: string;
            node_id_hex: string;
            connected_at: number;
            route: string;
        };
    };
    responses: never;
    parameters: {
        /** @description Unix-seconds cursor — return rows newer than this. */
        SinceTs: number;
        /** @description Max rows to return. */
        Limit: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getOpenapiYaml: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OpenAPI spec, raw YAML. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/yaml": string;
                };
            };
        };
    };
    getBootstrap: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bootstrap snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bootstrap"];
                };
            };
        };
    };
    getActivity: {
        parameters: {
            query?: {
                /** @description Unix-seconds cursor — return rows newer than this. */
                since?: components["parameters"]["SinceTs"];
                /** @description Max rows to return. */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Activity tail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityResponse"];
                };
            };
        };
    };
    getNetlog: {
        parameters: {
            query?: {
                /** @description Unix-seconds cursor — return rows newer than this. */
                since?: components["parameters"]["SinceTs"];
                /** @description Max rows to return. */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Egress tail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NetlogResponse"];
                };
            };
        };
    };
    getSavings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token usage + savings buckets from ~/.crabcc/usage.log. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        session?: components["schemas"]["SavingsBucket"];
                        last_24h?: components["schemas"]["SavingsBucket"];
                        all_time?: components["schemas"]["SavingsBucket"];
                        by_op?: {
                            [key: string]: components["schemas"]["SavingsBucket"];
                        };
                    };
                };
            };
        };
    };
    listAgents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agents. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentsResponse"];
                };
            };
        };
    };
    getAgentLog: {
        parameters: {
            query?: {
                since?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Log slice. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentLog"];
                };
            };
        };
    };
    getAgentTail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tail snapshot (free-form for now). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    getAgentInfo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agent info (free-form for now). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    killAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Kill snapshot (free-form for now). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    launchAgent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentLaunchRequest"];
            };
        };
        responses: {
            /** @description Launched. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentLaunchResponse"];
                };
            };
        };
    };
    listAgentProfiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profiles. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentProfilesResponse"];
                };
            };
        };
    };
    listAgentKills: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Kills. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentKillsResponse"];
                };
            };
        };
    };
    listAgentModels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Models. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentModelsResponse"];
                };
            };
        };
    };
    getOllamaKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Key snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OllamaKey"];
                };
            };
        };
    };
    getServices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Discovery report. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoveryReport"];
                };
            };
        };
    };
    getTelemetry: {
        parameters: {
            query?: {
                /** @description Unix-seconds cursor — return rows newer than this. */
                since?: components["parameters"]["SinceTs"];
                /** @description Max rows to return. */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Telemetry tail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelemetrySnapshot"];
                };
            };
        };
    };
    getOtlpHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OTLP health. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OtlpHealth"];
                };
            };
        };
    };
    reindexPwd: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reindex report. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReindexReport"];
                };
            };
        };
    };
    randomQuery: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Random query echo. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RandomQueryResponse"];
                };
            };
        };
    };
    getGraph: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Graph snapshot (free-form JSON for now). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    seedGraph: {
        parameters: {
            query?: {
                /** @description Number of seed (high-degree) symbols. Clamped to [2, 32]. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Seed snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeedSnapshot"];
                };
            };
        };
    };
    debugDump: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dump (free-form JSON). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    getMemoryRecent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Memory tail (free-form for now; tracked opaquely until the memory dashboard panel ships). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    getMemorySearch: {
        parameters: {
            query?: {
                q?: string;
                limit?: number;
                repo?: string;
                /** @description Ranking mode. Empty query always lists newest-first. */
                mode?: "hybrid" | "lexical" | "vector";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Aggregate ranked hits (free-form for now; tracked opaquely until the memory dashboard panel stabilises). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    getEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream (Content-Type text/event-stream). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
    getForgeConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Forge configuration snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForgeConfig"];
                };
            };
        };
    };
    listForgePrs: {
        parameters: {
            query?: {
                state?: "open" | "closed" | "all";
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PR list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrListResponse"];
                };
            };
        };
    };
    getForgePr: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PR detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrDetail"];
                };
            };
        };
    };
    getForgePrImpact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PR impact graph. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrImpactGraph"];
                };
            };
        };
    };
    getAnalyticsHotspots: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Hotspot list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HotspotsResponse"];
                };
            };
        };
    };
    getAnalyticsDeadcode: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dead code list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeadcodeResponse"];
                };
            };
        };
    };
    getWormholeSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of active wormhole sessions (may be empty). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WormholeSession"][];
                };
            };
        };
    };
}
