#!/usr/bin/env sh
# crabcc Ollama auth stack — bootstrap keys (issue #105)
#
# Generates a fresh OLLAMA_API_KEY + LITELLM_MASTER_KEY, writes them into
# install/ollama-stack/.env (gitignored), and prints the master key so the
# user can persist it to ${HOME}/.crabcc.local.api-key with chmod 400.
#
# Idempotent: if .env already has both keys, prints them without rotating.
# Pass `--rotate` to force regeneration (overwrites existing .env keys).
#
# Usage:
#   install/ollama-stack/init-keys.sh           # generate or print existing
#   install/ollama-stack/init-keys.sh --rotate  # force fresh keys
#   install/ollama-stack/init-keys.sh --quiet   # suppress save instructions
#
# Exit codes:
#   0  success
#   1  openssl missing or env file unwritable

set -eu

ROTATE=0
QUIET=0
for arg in "$@"; do
  case "$arg" in
    --rotate) ROTATE=1 ;;
    --quiet)  QUIET=1 ;;
    -h|--help)
      sed -n '2,18p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *)
      printf 'unknown flag: %s\n' "$arg" >&2
      exit 2
      ;;
  esac
done

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env"
LOCAL_KEY_FILE="${HOME}/.crabcc.local.api-key"

if ! command -v openssl >/dev/null 2>&1; then
  printf 'openssl is required to generate random keys. Install it and re-run.\n' >&2
  exit 1
fi

read_existing() {
  key="$1"
  [ -r "$ENV_FILE" ] || return 1
  awk -F= -v k="$key" '$1 == k { sub(/^[^=]*=/, ""); print; found=1 } END { exit !found }' "$ENV_FILE"
}

OLLAMA_API_KEY=""
LITELLM_MASTER_KEY=""

if [ "$ROTATE" -eq 0 ] && [ -r "$ENV_FILE" ]; then
  OLLAMA_API_KEY="$(read_existing OLLAMA_API_KEY 2>/dev/null || true)"
  LITELLM_MASTER_KEY="$(read_existing LITELLM_MASTER_KEY 2>/dev/null || true)"
fi

# Treat the .env.example placeholders as "no key" so we always rotate them.
case "$OLLAMA_API_KEY" in    changeme-*|"") OLLAMA_API_KEY="$(openssl rand -hex 32)" ; ROTATED=1 ;; esac
case "$LITELLM_MASTER_KEY" in changeme-*|"") LITELLM_MASTER_KEY="sk-$(openssl rand -hex 32)" ; ROTATED=1 ;; esac
ROTATED="${ROTATED:-0}"

if [ "$ROTATE" -eq 1 ]; then
  OLLAMA_API_KEY="$(openssl rand -hex 32)"
  LITELLM_MASTER_KEY="sk-$(openssl rand -hex 32)"
  ROTATED=1
fi

# Write atomically.
TMP="$(mktemp "${ENV_FILE}.XXXXXX")"
{
  printf '# Generated by install/ollama-stack/init-keys.sh — do not commit.\n'
  printf 'OLLAMA_API_KEY=%s\n' "$OLLAMA_API_KEY"
  printf 'LITELLM_MASTER_KEY=%s\n' "$LITELLM_MASTER_KEY"
  # Preserve any user-set port overrides if present.
  if [ -r "$ENV_FILE" ]; then
    grep -E '^(CADDY_PORT|LITELLM_PORT)=' "$ENV_FILE" 2>/dev/null || true
  fi
} > "$TMP"
chmod 600 "$TMP"
mv "$TMP" "$ENV_FILE"

# Seamless global persistence: write the user-facing api-key file so
# downstream callers (`crabcc agent --backend ollama`, the live
# dashboard's reveal panel, manual `cat` for piping) all read from a
# single canonical location. Idempotent: skip the write when the file
# already exists AND we didn't rotate this run, so the file's mtime
# stays meaningful for "when was this key first generated?".
if [ "$ROTATED" -eq 1 ] || [ ! -f "$LOCAL_KEY_FILE" ]; then
    printf '%s\n' "$LITELLM_MASTER_KEY" > "$LOCAL_KEY_FILE"
    # 0400 = owner-read-only. The file is already in $HOME so it's
    # never world-readable; locking permissions further is mainly to
    # signal "do not edit this by hand" — `init-keys.sh --rotate` is
    # the only supported mutation path.
    chmod 0400 "$LOCAL_KEY_FILE"
    PERSISTED=1
else
    PERSISTED=0
fi

if [ "$QUIET" -eq 1 ]; then
  printf '%s\n' "$LITELLM_MASTER_KEY"
  exit 0
fi

cat <<MSG
crabcc Ollama auth stack — keys ready

  .env file:           ${ENV_FILE}
  rotated this run:    $([ "$ROTATED" -eq 1 ] && echo yes || echo no — reused existing)

  LITELLM_MASTER_KEY:  ${LITELLM_MASTER_KEY}

  ^ This is the key your clients (and crabcc itself) send as
    Authorization: Bearer <key> on the OpenAI-compatible /v1 endpoints.

User-facing key file (auto-persisted):

  ${LOCAL_KEY_FILE}  ($([ "$PERSISTED" -eq 1 ] && echo "wrote 0400 this run" || echo "already present, untouched"))

Then in your shell rc:

  export OLLAMA_API_KEY="\$(cat ${LOCAL_KEY_FILE})"
  export OLLAMA_BASE_URL="http://localhost:\${LITELLM_PORT:-4000}"

Bring the stack up:

  cd ${SCRIPT_DIR}
  docker compose up -d --wait
MSG
