#!/usr/bin/env bash
# scripts/gen-summary.sh — generate a paste-ready markdown summary of
# the current branch state. Used by `task gen-summary`, called from
# `task prep-pr`, and refreshed by the pre-commit hook.
#
# Pure git ops + a couple of awk pipelines; ~200 ms typical, well under
# 1 s on huge diffs. No cargo, no network.
#
# Output:
#   .summary/gen-summary.md  (paste-ready for `gh pr create --body-file`)
#
# Usage:
#   bash scripts/gen-summary.sh                 # auto-detect base
#   bash scripts/gen-summary.sh --base origin/main
#   bash scripts/gen-summary.sh --quiet         # only emit the file
#
# Detects the PR base via (in order): --base flag, `gh pr view --json`,
# `git config branch.<curr>.merge`, fallback `origin/main`.
set -uo pipefail

BASE=""
QUIET=0
for arg in "$@"; do
    case "$arg" in
        --base)  shift; BASE="${1:-origin/main}" ;;
        --quiet) QUIET=1 ;;
        --help|-h)
            sed -n '2,17p' "$0" | sed 's/^# \?//'; exit 0 ;;
        *) echo "gen-summary: unknown arg $arg" >&2; exit 1 ;;
    esac
done

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null)" || {
    echo "gen-summary: not in a git repo" >&2; exit 1
}
cd "$REPO_ROOT"

OUT="$REPO_ROOT/.summary/gen-summary.md"
mkdir -p "$(dirname "$OUT")"

CURR_BRANCH="$(git rev-parse --abbrev-ref HEAD 2>/dev/null)"

# ── base resolution ──────────────────────────────────────────────────
if [ -z "$BASE" ]; then
    if command -v gh >/dev/null 2>&1; then
        BASE="$(gh pr view --json baseRefName --jq '.baseRefName' 2>/dev/null || true)"
        [ -n "$BASE" ] && BASE="origin/$BASE"
    fi
fi
[ -z "$BASE" ] && BASE="origin/main"

# Resolve to a commit; if the base ref doesn't exist, fall back gently.
if ! git rev-parse --verify "$BASE" >/dev/null 2>&1; then
    BASE="origin/main"
    git rev-parse --verify "$BASE" >/dev/null 2>&1 || BASE="HEAD~10"
fi

MERGE_BASE="$(git merge-base "$BASE" HEAD 2>/dev/null)" || MERGE_BASE="$BASE"
AHEAD="$(git rev-list --count "$MERGE_BASE..HEAD" 2>/dev/null || echo 0)"
COMMITS="$(git log --format='%h %s' "$MERGE_BASE..HEAD" 2>/dev/null)"

# ── files-changed by crate / top-level dir ──────────────────────────
FILES_RAW="$(git diff --name-only "$MERGE_BASE...HEAD" 2>/dev/null)"
FILES_COUNT="$(echo "$FILES_RAW" | grep -c . || true)"

# Group changes by top-level dir (or `crates/<name>` for crates).
GROUPED="$(echo "$FILES_RAW" | awk -F/ '
    NF == 0 { next }
    $1 == "crates" && NF >= 2 { print "crates/" $2; next }
    { print $1 }
' | sort | uniq -c | sort -rn)"

# Numstat: added/deleted lines per file → totals.
STATS="$(git diff --numstat "$MERGE_BASE...HEAD" 2>/dev/null \
    | awk '$1 != "-" && $2 != "-" { a += $1; d += $2 } END { print a"+ / "d"-" }')"
[ -z "$STATS" ] && STATS="0+ / 0-"

# ── issue references in commit messages ─────────────────────────────
ISSUES="$(echo "$COMMITS" | grep -oE '#[0-9]+' | sort -u | tr '\n' ' ' | sed 's/ $//')"

# ── prep-pr gate snapshot (best-effort) ─────────────────────────────
PREP_STATUS="not run yet"
PREP_LOG="$REPO_ROOT/.summary/prep-pr.txt"
if [ -f "$PREP_LOG" ]; then
    if tail -1 "$PREP_LOG" | grep -q "all .* checks passed"; then
        PREP_STATUS="✓ all gates passed ($(date -r "$PREP_LOG" '+%Y-%m-%d %H:%M'))"
    elif tail -1 "$PREP_LOG" | grep -qE "[0-9]+/[0-9]+ checks failed"; then
        PREP_STATUS="✗ $(tail -1 "$PREP_LOG" | grep -oE '[0-9]+/[0-9]+ checks failed')"
    else
        PREP_STATUS="ran but no clear verdict — see $PREP_LOG"
    fi
fi

# ── cargo workspace version ─────────────────────────────────────────
CARGO_VER="$(awk -F'"' '/^\[workspace.package\]/{f=1} f && /^version *=/ {print $2; exit}' Cargo.toml 2>/dev/null || true)"

# ── render ──────────────────────────────────────────────────────────
{
    echo "<!-- Generated by scripts/gen-summary.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ) -->"
    echo
    echo "## Summary"
    echo
    echo "Branch \`$CURR_BRANCH\` is **$AHEAD commit$([ "$AHEAD" = "1" ] || echo "s") ahead** of \`$BASE\`."
    if [ -n "$ISSUES" ]; then
        echo "Refs / closes: $ISSUES"
    fi
    if [ -n "$CARGO_VER" ]; then
        echo "Workspace version: \`$CARGO_VER\`"
    fi
    echo
    echo "**Files changed**: $FILES_COUNT  ·  **lines**: $STATS"
    echo
    if [ -n "$GROUPED" ]; then
        echo "### Changes by area"
        echo
        echo '| count | area |'
        echo '|------:|------|'
        echo "$GROUPED" | awk '{ n=$1; $1=""; sub(/^ /, ""); printf "| %5d | %s |\n", n, $0 }'
        echo
    fi
    if [ -n "$COMMITS" ]; then
        echo "### Commits"
        echo
        echo "$COMMITS" | awk '{ printf "- `%s` %s\n", $1, substr($0, length($1)+2) }'
        echo
    fi
    echo "### Local gates"
    echo
    echo "- prep-pr: $PREP_STATUS"
    echo
    echo "<!-- Edit this file freely; it is overwritten on each \`task gen-summary\` /"
    echo "     pre-commit run. Pipe through \`gh pr create --body-file .summary/gen-summary.md\`. -->"
} > "$OUT"

if [ "$QUIET" = "0" ]; then
    echo "gen-summary: wrote $OUT  ·  $AHEAD commit(s) · $FILES_COUNT file(s) · $STATS · base=$BASE"
fi
