//! Helpers for laying out the per-user crabcc bin shim directory and
//! composing the PATH spawned agent processes inherit.
//!
//! Lives in `crabcc-core` (not `crabcc-viz`, where these used to live)
//! because the agent path matters anywhere we spawn subprocesses —
//! `crabcc agent`, the MCP server's tool-call dispatch — not just the
//! `crabcc serve` web UI. Keeping these in viz forced cli to take a
//! transitive dep on the entire web stack just to set PATH.

use std::path::{Path, PathBuf};

use anyhow::{Context, Result};

/// Where we install our shim/symlink directory. Goes onto the agent's
/// PATH ahead of `~/.cargo/bin` and `~/.local/bin` so a `crabcc`
/// invocation from inside an agent's `Bash` tool call resolves to the
/// version we want, not whatever's in the user's primary install.
pub const CRABCC_BIN_DIR: &str = ".crabcc/bin";

/// Set up `~/.crabcc/bin/` with symlinks for the binaries we want
/// agent subprocesses to find on PATH. Today we install:
///
///   - `crabcc` -> the running crabcc binary (so the agent's Bash tool
///     calls hit the same version that started `crabcc serve` /
///     `crabcc agent`).
///   - `cc` -> a wrapper script that just execs `crabcc "$@"`.
///
/// The wrapper for `cc` is a written script (not a symlink) because
/// `cc` is reserved on most Unixes for the C compiler — symlinking
/// it would shadow the C toolchain. Putting a hand-written script
/// makes the override explicit and easier to remove (`rm`) later.
///
/// Idempotent: symlinks pointing at the right target are left alone.
/// Returns the bin-dir path so callers can append it to `PATH`.
pub fn ensure_bin_dir(home: &Path) -> Result<PathBuf> {
    let bin_dir = home.join(CRABCC_BIN_DIR);
    std::fs::create_dir_all(&bin_dir).with_context(|| format!("create {}", bin_dir.display()))?;

    // Resolve the running `crabcc` binary. `current_exe` is reliable
    // on macOS + Linux (which is what we ship for). On Windows it
    // might be a TrampolineExe; we don't ship Windows agents today.
    if let Ok(self_exe) = std::env::current_exe() {
        symlink_idempotent(&self_exe, &bin_dir.join("crabcc"))?;
    }

    // `cc` shim — hand-written, executable. Re-write if missing or stale.
    let cc_path = bin_dir.join("cc");
    let want = "#!/bin/sh\n\
                # Generated by crabcc; safe to delete. \
                Re-created on next `crabcc serve` or `crabcc agent` start.\n\
                exec crabcc \"$@\"\n";
    let needs_write = std::fs::read_to_string(&cc_path)
        .map(|s| s != want)
        .unwrap_or(true);
    if needs_write {
        std::fs::write(&cc_path, want).with_context(|| format!("write {}", cc_path.display()))?;
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mut p = std::fs::metadata(&cc_path)?.permissions();
            p.set_mode(0o755);
            std::fs::set_permissions(&cc_path, p)?;
        }
    }

    Ok(bin_dir)
}

#[cfg(unix)]
fn symlink_idempotent(target: &Path, link: &Path) -> Result<()> {
    if let Ok(existing) = std::fs::read_link(link) {
        if existing == target {
            return Ok(());
        }
    }
    if link.exists() || std::fs::symlink_metadata(link).is_ok() {
        std::fs::remove_file(link).ok();
    }
    std::os::unix::fs::symlink(target, link)
        .with_context(|| format!("symlink {} -> {}", link.display(), target.display()))?;
    Ok(())
}

#[cfg(not(unix))]
fn symlink_idempotent(_target: &Path, _link: &Path) -> Result<()> {
    // Windows symlinks need elevated perms; skip silently — the agent
    // PATH extension still helps on Windows because `~/.cargo/bin/`
    // already has the right binary.
    Ok(())
}

/// Compose the PATH string we want spawned agent processes to inherit.
/// Prepend `~/.crabcc/bin`, `~/.cargo/bin`, `~/.local/bin` to whatever
/// the parent already has. We don't *replace* PATH — just bias the
/// front of it — so the agent still finds `git`, `gh`, `jq`, `rg`,
/// etc. that the user had on PATH already.
pub fn agent_path(home: &Path) -> String {
    let mut out: Vec<PathBuf> = Vec::new();
    out.push(home.join(CRABCC_BIN_DIR));
    out.push(home.join(".cargo").join("bin"));
    out.push(home.join(".local").join("bin"));
    if let Ok(existing) = std::env::var("PATH") {
        for p in std::env::split_paths(&existing) {
            if !out.iter().any(|x| x == &p) {
                out.push(p);
            }
        }
    }
    std::env::join_paths(out)
        .map(|s| s.to_string_lossy().to_string())
        .unwrap_or_default()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ensure_bin_dir_creates_dir_and_cc_shim() {
        let home = tempfile::tempdir().unwrap();
        let dir = ensure_bin_dir(home.path()).unwrap();
        assert!(dir.starts_with(home.path()));
        assert!(dir.exists());
        let cc = dir.join("cc");
        assert!(cc.exists(), "cc shim missing");
        let body = std::fs::read_to_string(&cc).unwrap();
        assert!(body.contains("exec crabcc"), "cc body: {body:?}");
    }

    #[test]
    fn ensure_bin_dir_is_idempotent() {
        let home = tempfile::tempdir().unwrap();
        let dir1 = ensure_bin_dir(home.path()).unwrap();
        let cc_mtime = std::fs::metadata(dir1.join("cc"))
            .unwrap()
            .modified()
            .unwrap();
        std::thread::sleep(std::time::Duration::from_millis(10));
        let dir2 = ensure_bin_dir(home.path()).unwrap();
        assert_eq!(dir1, dir2);
        let cc_mtime2 = std::fs::metadata(dir2.join("cc"))
            .unwrap()
            .modified()
            .unwrap();
        assert_eq!(cc_mtime, cc_mtime2, "cc shim should not be re-written");
    }

    #[test]
    fn agent_path_prepends_crabcc_bin_dir() {
        let home = tempfile::tempdir().unwrap();
        let path = agent_path(home.path());
        let first_segments: Vec<&str> = path.split(':').take(3).collect();
        assert!(
            first_segments[0].ends_with(CRABCC_BIN_DIR),
            "first segment should be the crabcc bin dir: {path:?}"
        );
        assert!(first_segments[1].ends_with(".cargo/bin"));
        assert!(first_segments[2].ends_with(".local/bin"));
    }
}
