#!/usr/bin/env bash
# Push .github/dependabot.yml to peterlodri-sec/rag-stack.
#
# rag-stack ecosystem inventory (verified via gh api on 2026-05-17):
#   - pyproject.toml at repo root (uv-managed; PyPI ecosystem via pip)
#   - .github/workflows/{codex-review,docs-deploy,lint,publish-images}.yml (github-actions)
#   - Dockerfiles ship container images (docker ecosystem; root directory)
#
# This script creates a branch, commits the dependabot.yml via the contents API,
# and opens a PR. Idempotent: if the branch already exists, it updates the file
# in place; if dependabot.yml already exists, it does nothing.
set -euo pipefail

REPO="peterlodri-sec/rag-stack"
BRANCH="chore/dependabot"
PATH_IN_REPO=".github/dependabot.yml"
COMMIT_MSG="chore: add Dependabot config for pip, github-actions, and docker"

DEPENDABOT_YML=$(cat <<'YAML'
# Managed by orchestrator/add-rag-stack-dependabot.sh.
# Weekly grouped Dependabot updates across the three ecosystems present in rag-stack:
#   - pip          (pyproject.toml at repo root)
#   - github-actions (.github/workflows/*.yml)
#   - docker       (Dockerfiles in repo root and subdirectories)
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      python-minor-and-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
      python-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
      include: "scope"
    groups:
      actions-minor-and-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(docker)"
      include: "scope"
    groups:
      docker-minor-and-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
YAML
)

WORK_DIR=$(mktemp -d)
trap 'rm -rf "${WORK_DIR}"' EXIT

echo "==> Cloning ${REPO} (shallow) into ${WORK_DIR}..."
gh repo clone "${REPO}" "${WORK_DIR}/repo" -- --depth 1 --no-tags >/dev/null

cd "${WORK_DIR}/repo"
git fetch origin "${BRANCH}" 2>/dev/null && \
  git checkout "${BRANCH}" || git checkout -b "${BRANCH}"

mkdir -p "$(dirname "${PATH_IN_REPO}")"
printf '%s\n' "${DEPENDABOT_YML}" > "${PATH_IN_REPO}"

if git diff --quiet -- "${PATH_IN_REPO}"; then
  echo "    ${PATH_IN_REPO} unchanged on ${BRANCH}; nothing to push."
  exit 0
fi

git add "${PATH_IN_REPO}"
git -c user.name="orchestrator-bot" \
    -c user.email="orchestrator@peterlodri-sec.local" \
    commit -m "${COMMIT_MSG}"
git push -u origin "${BRANCH}"

echo "==> Opening PR..."
if ! gh pr view "${BRANCH}" --repo "${REPO}" >/dev/null 2>&1; then
  gh pr create \
    --repo "${REPO}" \
    --base main \
    --head "${BRANCH}" \
    --title "chore: add Dependabot config" \
    --body "Adds .github/dependabot.yml covering pip (pyproject.toml), github-actions, and docker on a weekly schedule with grouped minor/patch updates. Generated by orchestrator/add-rag-stack-dependabot.sh."
else
  echo "    PR already open for ${BRANCH}."
fi
